# Generated by Django 5.1.1 on 2024-10-10 19:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('level', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=40)),
                ('per_diem', models.DecimalField(decimal_places=2, max_digits=8)),
                ('local_running', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estacode', models.DecimalField(decimal_places=2, max_digits=8)),
                ('assumption_of_duty', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='PFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='core.department')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Employee ID')),
                ('ippis_number', models.CharField(max_length=50, unique=True, verbose_name='IPPIS Number')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('in_app_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='In-App Email')),
                ('in_app_chat_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='In-App Chat Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('date_of_first_appointment', models.DateField(blank=True, null=True, verbose_name='Date of First Appointment')),
                ('date_of_retirement', models.DateField(blank=True, null=True, verbose_name='Date of Retirement')),
                ('active_status', models.BooleanField(default=True, verbose_name='Active Status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('current_role', models.CharField(choices=[('DG', 'Director General'), ('DIR', 'Director'), ('ZD', 'Zonal Director'), ('SC', 'State Coordinator'), ('STAFF', 'Staff')], default='STAFF', max_length=5)),
                ('access_type', models.CharField(choices=[('staff', 'Staff'), ('adhoc', 'Ad Hoc')], default='staff', max_length=20, verbose_name='Access Type')),
                ('password_change_required', models.BooleanField(default=False)),
                ('current_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_employees', to='auth.group', verbose_name='Current Group')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('current_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department', verbose_name='Department')),
                ('current_grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.gradelevel', verbose_name='Grade Level')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='OfficialAppointment',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('cadre', models.CharField(choices=[('O', 'OFFICER'), ('E', 'EXECUTIVE'), ('S', 'SECRETARIAL'), ('C', 'CLERICAL'), ('D', 'DRIVER')], max_length=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gradelevel')),
            ],
            options={
                'verbose_name': 'Official Appointment',
                'verbose_name_plural': 'Official Appointments',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.state')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_unit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_zone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.zone'),
        ),
        migrations.AddField(
            model_name='employee',
            name='current_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zone'),
        ),
    ]
