# Generated by Django 5.1 on 2024-08-30 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='access_type',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('GUEST', 'Guest'), ('RETIRED', 'Retired')], default='STAFF', max_length=10, verbose_name='Access Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bvn',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='BVN'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On Leave', 'On Leave')], default='Active', max_length=20, verbose_name='Employment Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Highest Qualification'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.lga', verbose_name='LGA'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='next_of_kin_name',
            field=models.CharField(max_length=200, verbose_name='Next of Kin Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='next_of_kin_phone_number',
            field=models.CharField(max_length=15, verbose_name='Next of Kin Phone Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='next_of_kin_relationship',
            field=models.CharField(max_length=50, verbose_name='Next of Kin Relationship'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='retirement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Retirement Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.role', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Spouse Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='spouse_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Spouse Phone Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='year_of_graduation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of Graduation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.zone', verbose_name='Zone'),
        ),
    ]
