# Generated by Django 5.1 on 2024-09-01 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employee_access_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bvn',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='highest_qualification',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lga',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='next_of_kin_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='next_of_kin_phone_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='next_of_kin_relationship',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='spouse_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='spouse_phone_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='state',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='year_of_graduation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='zone',
        ),
        migrations.CreateModel(
            name='EmployeeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_made', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Gender')),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20, verbose_name='Marital Status')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('employment_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Temporary', 'Temporary')], default='Full Time', max_length=20, verbose_name='Employment Type')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Hire Date')),
                ('highest_qualification', models.CharField(blank=True, max_length=100, null=True, verbose_name='Highest Qualification')),
                ('institution', models.CharField(blank=True, max_length=200, null=True, verbose_name='Institution')),
                ('year_of_graduation', models.IntegerField(blank=True, null=True, verbose_name='Year of Graduation')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Emergency Contact Name')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Emergency Contact Relationship')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Emergency Contact Phone')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Account Number')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nationality')),
                ('state_of_origin', models.CharField(blank=True, max_length=50, null=True, verbose_name='State of Origin')),
                ('local_government_area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local Government Area')),
                ('employee_grade_level', models.CharField(blank=True, max_length=20, null=True, verbose_name='Employee Grade Level')),
                ('date_of_first_appointment', models.DateField(blank=True, null=True, verbose_name='Date of First Appointment')),
                ('date_of_present_appointment', models.DateField(blank=True, null=True, verbose_name='Date of Present Appointment')),
                ('professional_qualifications', models.TextField(blank=True, null=True, verbose_name='Professional Qualifications')),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True, verbose_name='Blood Group')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Allergies')),
                ('pension_fund_administrator', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pension Fund Administrator')),
                ('pension_account_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pension Account Number')),
                ('last_promotion_date', models.DateField(blank=True, null=True, verbose_name='Last Promotion Date')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Detail',
                'verbose_name_plural': 'Employee Details',
            },
        ),
    ]
