# Generated by Django 5.1.1 on 2024-10-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_file_filehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone Number'),
        ),
    ]
