# Generated by Django 5.1 on 2024-09-02 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_employee_department_alter_employee_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='highest_qualification',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='year_of_graduation',
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL),
        ),
    ]
