# Generated by Django 5.1 on 2024-09-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_employeedetail_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('DG', 'Director General'), ('DIR', 'Director'), ('ZD', 'Zonal Director'), ('HOD', 'Head of Department'), ('HOU', 'Head of Unit'), ('STAFF', 'Staff'), ('IT_ADMIN', 'IT Admin')], default='STAFF', max_length=20),
        ),
    ]
