# Generated by Django 5.1 on 2024-09-03 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='blood_group',
        ),
        migrations.AddField(
            model_name='employee',
            name='current_rank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rank'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_confirmation',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Confirmation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(verbose_name='Date of First Appointment'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('AWOL', 'Absent Without Leave'), ('On Leave', 'On Leave')], default='Active', max_length=20, verbose_name='Employment Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='bank_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bank', verbose_name='Bank Name'),
        ),
    ]
