# Generated by Django 5.1 on 2024-09-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bank_remove_employee_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='access_type',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('RETIRED', 'Retired')], default='STAFF', max_length=10, verbose_name='Access Type'),
        ),
    ]
