# Generated by Django 5.1 on 2024-09-03 10:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_employee_access_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('employee_id', models.CharField(db_index=True, max_length=20, verbose_name='Employee ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('date_joined', models.DateField(verbose_name='Date of First Appointment')),
                ('access_type', models.CharField(choices=[('STAFF', 'Staff'), ('RETIRED', 'Retired')], default='STAFF', max_length=10, verbose_name='Access Type')),
                ('role', models.CharField(choices=[('DG', 'Director General'), ('DIR', 'Director'), ('ZD', 'Zonal Director'), ('HOD', 'Head of Department'), ('HOU', 'Head of Unit'), ('STAFF', 'Staff'), ('IT_ADMIN', 'IT Admin')], default='STAFF', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='Gender')),
                ('current_rank', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rank')),
                ('employment_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('AWOL', 'Absent Without Leave'), ('On Leave', 'On Leave')], default='Active', max_length=20, verbose_name='Employment Status')),
                ('date_of_confirmation', models.DateField(blank=True, null=True, verbose_name='Date of Confirmation')),
                ('retirement_date', models.DateField(blank=True, null=True, verbose_name='Retirement Date')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.department', verbose_name='Department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user',
                'verbose_name_plural': 'historical users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
