# Generated by Django 5.1 on 2024-09-03 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_historicalemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_workflows', to='core.workflowstep'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='steps',
            field=models.ManyToManyField(related_name='workflows', through='core.WorkflowStepOrder', to='core.workflowstep'),
        ),
    ]
