# Generated by Django 5.1 on 2024-09-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_department_parent_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ippis_number',
            field=models.IntegerField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='ippis_number',
            field=models.IntegerField(blank=True, db_index=True, max_length=8, null=True),
        ),
    ]
