# Generated by Django 5.1 on 2024-09-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_employee_ippis_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On Leave', 'On Leave'), ('LOA', 'Leave of Absence'), ('Secondment', 'Secondment'), ('AWOL', 'Absent Without Leave'), ('Illness', 'Illness')], default='Active', max_length=20, verbose_name='Employment Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ippis_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='employment_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On Leave', 'On Leave'), ('LOA', 'Leave of Absence'), ('Secondment', 'Secondment'), ('AWOL', 'Absent Without Leave'), ('Illness', 'Illness')], default='Active', max_length=20, verbose_name='Employment Status'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='ippis_number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
