# Generated by Django 5.1 on 2024-09-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_employee_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('DG OFFICE', 'Director General Office'), ('SERVICE', 'Service Department'), ('PROGRAMME', 'Programme Department'), ('ZONAL', 'Zonal Department'), ('BRANCH', 'Branch'), ('UNIT', 'Unit')], default='SERVICE', max_length=20),
        ),
        migrations.AddField(
            model_name='lga',
            name='code',
            field=models.CharField(default=1, max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='code',
            field=models.CharField(default=1, max_length=2, unique=True),
            preserve_default=False,
        ),
    ]
