# Generated by Django 5.1 on 2024-09-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_department_code_department_type_lga_code_state_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
    ]
