# Generated by Django 5.1 on 2024-09-09 10:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_emploqyee_leave_employee_remove_task_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='current_step',
        ),
        migrations.AddField(
            model_name='workflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflow',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='workflow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.workflow'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='current_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_instances', to='core.workflowstep'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='core.workflow'),
        ),
        migrations.CreateModel(
            name='StepLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_reusable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('required_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.custompermission')),
                ('required_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role')),
            ],
            options={
                'verbose_name_plural': 'Step libraries',
            },
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='library_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.steplibrary'),
        ),
        migrations.DeleteModel(
            name='WorkflowStepOrder',
        ),
    ]
