# Generated by Django 5.1.1 on 2024-10-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_attachments/', verbose_name='File')),
                ('filename', models.CharField(max_length=255, verbose_name='File Name')),
            ],
            options={
                'verbose_name': 'Chat Attachment',
                'verbose_name_plural': 'Chat Attachments',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Message Content')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('EMAIL_SENT', 'Email Sent'), ('EMAIL_READ', 'Email Read'), ('CHAT_MESSAGE_SENT', 'Chat Message Sent'), ('CHAT_MESSAGE_READ', 'Chat Message Read'), ('SENT', 'Message Sent'), ('READ', 'Message Read'), ('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('ANNOUNCEMENT_CREATED', 'Announcement Created'), ('NEWSLETTER_PUBLISHED', 'Newsletter Published')], max_length=20, verbose_name='Action Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
            ],
            options={
                'verbose_name': 'Communication Log',
                'verbose_name_plural': 'Communication Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Department Announcement',
                'verbose_name_plural': 'Department Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='email_attachments/', verbose_name='File')),
                ('filename', models.CharField(max_length=255, verbose_name='File Name')),
            ],
            options={
                'verbose_name': 'Email Attachment',
                'verbose_name_plural': 'Email Attachments',
            },
        ),
        migrations.CreateModel(
            name='InAppChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_group_chat', models.BooleanField(default=False, verbose_name='Is Group Chat')),
                ('group_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Group Name')),
            ],
            options={
                'verbose_name': 'In-App Chat',
                'verbose_name_plural': 'In-App Chats',
            },
        ),
        migrations.CreateModel(
            name='InAppEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Email Body')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('is_draft', models.BooleanField(default=False, verbose_name='Is Draft')),
            ],
            options={
                'verbose_name': 'In-App Email',
                'verbose_name_plural': 'In-App Emails',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('MESSAGE', 'New Message'), ('TASK', 'Task Assignment'), ('REMINDER', 'Reminder'), ('ANNOUNCEMENT', 'Announcement'), ('SYSTEM', 'System Notification')], max_length=20, verbose_name='Notification Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Related Object ID')),
                ('related_object_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Related Object Type')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10, verbose_name='Priority')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-due_date'],
            },
        ),
    ]
