# Generated by Django 5.1.1 on 2024-10-10 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.ManyToManyField(blank=True, related_name='read_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Read By'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communication.chatmessage', verbose_name='Chat Message'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='departmentannouncement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='departmentannouncement',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='inappchat',
            name='participants',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.inappchat', verbose_name='Chat'),
        ),
        migrations.AddField(
            model_name='inappemail',
            name='bcc',
            field=models.ManyToManyField(blank=True, related_name='bcc_emails', to=settings.AUTH_USER_MODEL, verbose_name='BCC'),
        ),
        migrations.AddField(
            model_name='inappemail',
            name='cc',
            field=models.ManyToManyField(blank=True, related_name='cc_emails', to=settings.AUTH_USER_MODEL, verbose_name='CC'),
        ),
        migrations.AddField(
            model_name='inappemail',
            name='is_read',
            field=models.ManyToManyField(blank=True, related_name='read_emails', to=settings.AUTH_USER_MODEL, verbose_name='Read By'),
        ),
        migrations.AddField(
            model_name='inappemail',
            name='parent_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='communication.inappemail', verbose_name='Parent Email'),
        ),
        migrations.AddField(
            model_name='inappemail',
            name='recipients',
            field=models.ManyToManyField(related_name='received_emails', to=settings.AUTH_USER_MODEL, verbose_name='Recipients'),
        ),
        migrations.AddField(
            model_name='inappemail',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communication.inappemail', verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_newsletters', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='newsletters', to='core.department', verbose_name='Target Departments'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_tasks', to='core.department', verbose_name='Department'),
        ),
    ]
