# Generated by Django 5.1.1 on 2024-10-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed')], default='active', max_length=15),
        ),
    ]
